export const ADD_ERROR = "ADD_ERROR";
export const REMOVE_ERROR = "REMOVE_ERROR";
export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOAD_TECHNIQUES = "LOAD_TECHNIQUES";
export const REMOVE_TECHNIQUES = "REMOVE_TECHNIQUES";
export const EDIT_TECHNIQUE = "EDIT_TECHNIQUE";
export const SHOW_TECHNIQUE = "SHOW_TECHNIQUE";
export const CREATE_TECHNIQUE = "CREATE_TECHNIQUE";

export const LOAD_SEQUENCES = "LOAD_SEQUENCES";
export const REMOVE_SEQUENCES = "REMOVE_SEQUENCES";
export const EDIT_SEQUENCE = "EDIT_SEQUENCE";
export const SHOW_SEQUENCE = "SHOW_SEQUENCE";
export const CREATE_SEQUENCE = "CREATE_SEQUENCE";

export const ADD_SEQUENCE = "ADD_SEQUENCE";
export const REMOVE_SEQUENCE = "REMOVE_SEQUENCE";

export const ADD_REF = "ADD_REF";
export const REMOVE_REFS = "REMOVE_REFS";
export const REMOVE_REF = "REMOVE_REF";

export const UPDATE_USER_LIKES = "UPDATE_USER_LIKES";

export const UPDATE_SHARE_STATE = "UPDATE_SHARE_STATE";

export const SEND_MESSAGE = "SEND_MESSAGE";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";